# Generated by Django 4.1.4 on 2023-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=128, verbose_name='Alias')),
                ('url_for_redirect', models.CharField(default='', max_length=512, verbose_name='Url for Redirect')),
                ('email', models.CharField(default='', max_length=128, verbose_name='Email')),
                ('status_code', models.IntegerField(default=200, verbose_name='Status Code')),
                ('email_number', models.IntegerField(default=1, verbose_name='Email Number in Sequence')),
                ('email_type', models.CharField(default='A', help_text='A/B Test', max_length=3, verbose_name='Email type in Sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='', max_length=128, unique=True, verbose_name='Alias')),
                ('webhook_url', models.CharField(default='', max_length=512, verbose_name='Webhook Url')),
                ('track_all_clicks', models.BooleanField(default=False, verbose_name='Track all clicks')),
                ('unique_click_by_link', models.BooleanField(default=False, verbose_name='Unique click by link')),
            ],
        ),
    ]
