# Generated by Django 4.1.4 on 2023-01-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alias', models.CharField(max_length=128)),
                ('WebHook Url', models.CharField(max_length=512)),
                ('Email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alias', models.CharField(max_length=128, unique=True)),
                ('WebHook Url', models.CharField(max_length=512)),
            ],
        ),
    ]
