# Generated by Django 4.1.4 on 2023-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickrecord',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
