# Generated by Django 4.1.4 on 2023-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktrack', '0002_clickrecord_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickrecord',
            name='Alias',
        ),
        migrations.RemoveField(
            model_name='clickrecord',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='clickrecord',
            name='WebHook Url',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='Alias',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='WebHook Url',
        ),
        migrations.AddField(
            model_name='clickrecord',
            name='url_for_redirect',
            field=models.CharField(default='', max_length=512, verbose_name='WebHook Url'),
        ),
        migrations.AddField(
            model_name='relation',
            name='webhook_url',
            field=models.CharField(default='', max_length=512, verbose_name='WebHook Url'),
        ),
        migrations.AlterField(
            model_name='clickrecord',
            name='status_code',
            field=models.IntegerField(default=200, verbose_name='Status Code'),
        ),
        migrations.AddField(
            model_name='clickrecord',
            name='alias',
            field=models.CharField(default='', max_length=128, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='clickrecord',
            name='email',
            field=models.CharField(default='', max_length=128, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='relation',
            name='alias',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='Alias'),
        ),
    ]
