# Generated by Django 4.1.4 on 2023-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktrack', '0003_remove_clickrecord_alias_remove_clickrecord_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickrecord',
            name='email_number',
            field=models.IntegerField(default=1, verbose_name='Email Number in Siquence'),
        ),
        migrations.AddField(
            model_name='clickrecord',
            name='email_type',
            field=models.CharField(default='A', help_text='A/B Test', max_length=3, verbose_name='Email tyepe in Siquence'),
        ),
    ]
