# Generated by Django 4.1.4 on 2023-01-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktrack', '0005_relation_track_all_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='unique_click_by_link',
            field=models.BooleanField(default=False, verbose_name='Unique click by link'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='track_all_clicks',
            field=models.BooleanField(default=False, verbose_name='Track all clicks'),
        ),
    ]
